#ifndef GUARD_CONSTANTS_CARD_IDS_H
#define GUARD_CONSTANTS_CARD_IDS_H

#define CARD_NONE                                   0x0000
#define BLUE_EYES_WHITE_DRAGON                      0x0001
#define MYSTICAL_ELF                                0x0002
#define HITOTSU_ME_GIANT                            0x0003
#define BABY_DRAGON                                 0x0004
#define RYU_KISHIN                                  0x0005
#define FERAL_IMP                                   0x0006
#define WINGED_DRAGON_GUARDIAN_OF_THE_FORTRESS_1    0x0007
#define MUSHROOM_MAN                                0x0008
#define SHADOW_SPECTER                              0x0009
#define BLACKLAND_FIRE_DRAGON                       0x000A
#define SWORD_ARM_OF_DRAGON                         0x000B
#define SWAMP_BATTLEGUARD                           0x000C
#define THE_STERN_MYSTIC                            0x000D
#define BATTLE_STEER                                0x000E
#define FLAME_SWORDSMAN                             0x000F
#define TIME_WIZARD                                 0x0010
#define RIGHT_LEG_OF_THE_FORBIDDEN_ONE              0x0011
#define LEFT_LEG_OF_THE_FORBIDDEN_ONE               0x0012
#define RIGHT_ARM_OF_THE_FORBIDDEN_ONE              0x0013
#define LEFT_ARM_OF_THE_FORBIDDEN_ONE               0x0014
#define EXODIA_THE_FORBIDDEN_ONE                    0x0015
#define SUMMONED_SKULL                              0x0016
#define THE_WICKED_WORM_BEAST                       0x0017
#define SKULL_SERVANT                               0x0018
#define HORN_IMP                                    0x0019
#define BATTLE_OX                                   0x001A
#define BEAVER_WARRIOR                              0x001B
#define ROCK_OGRE_GROTTO_1                          0x001C
#define MOUNTAIN_WARRIOR                            0x001D
#define ZOMBIE_WARRIOR                              0x001E
#define KOUMORI_DRAGON                              0x001F
#define TWO_HEADED_KING_REX                         0x0020
#define JUDGE_MAN                                   0x0021
#define SAGGI_THE_DARK_CLOWN                        0x0022
#define DARK_MAGICIAN                               0x0023
#define THE_SNAKE_HAIR                              0x0024
#define GAIA_THE_DRAGON_CHAMPION                    0x0025
#define GAIA_THE_FIERCE_KNIGHT                      0x0026
#define CURSE_OF_DRAGON                             0x0027
#define DRAGON_PIPER                                0x0028
#define CELTIC_GUARDIAN                             0x0029
#define ILLUSIONIST_FACELESS_MAGE                   0x002A
#define KARBONALA_WARRIOR                           0x002B
#define ROGUE_DOLL                                  0x002C
#define OSCILLO_HERO_2                              0x002D
#define GRIFFORE                                    0x002E
#define TORIKE                                      0x002F
#define SANGAN                                      0x0030
#define BIG_INSECT                                  0x0031
#define BASIC_INSECT                                0x0032
#define ARMORED_LIZARD                              0x0033
#define HERCULES_BEETLE                             0x0034
#define KILLER_NEEDLE                               0x0035
#define GOKIBORE                                    0x0036
#define GIANT_FLEA                                  0x0037
#define LARVAE_MOTH                                 0x0038
#define GREAT_MOTH                                  0x0039
#define KURIBOH                                     0x003A
#define MAMMOTH_GRAVEYARD                           0x003B
#define GREAT_WHITE                                 0x003C
#define WOLF                                        0x003D
#define HARPIE_LADY                                 0x003E
#define HARPIE_LADY_SISTERS                         0x003F
#define TIGER_AXE                                   0x0040
#define SILVER_FANG                                 0x0041
#define KOJIKOCY                                    0x0042
#define PERFECTLY_ULTIMATE_GREAT_MOTH               0x0043
#define GAROOZIS                                    0x0044
#define THOUSAND_DRAGON                             0x0045
#define FIEND_KRAKEN                                0x0046
#define JELLYFISH                                   0x0047
#define COCOON_OF_EVOLUTION                         0x0048
#define KAIRYU_SHIN                                 0x0049
#define GIANT_SOLDIER_OF_STONE                      0x004A
#define MAN_EATING_PLANT                            0x004B
#define KROKODILUS                                  0x004C
#define GRAPPLER                                    0x004D
#define AXE_RAIDER                                  0x004E
#define MEGAZOWLER                                  0x004F
#define URABY                                       0x0050
#define CRAWLING_DRAGON_2                           0x0051
#define RED_EYES_B_DRAGON                           0x0052
#define CASTLE_OF_DARK_ILLUSIONS                    0x0053
#define REAPER_OF_THE_CARDS                         0x0054
#define KING_OF_YAMIMAKAI                           0x0055
#define BAROX                                       0x0056
#define DARK_CHIMERA                                0x0057
#define METAL_GUARDIAN                              0x0058
#define CATAPULT_TURTLE                             0x0059
#define GYAKUTENNO_MEGAMI                           0x005A
#define MYSTIC_HORSEMAN                             0x005B
#define RABID_HORSEMAN                              0x005C
#define ZANKI                                       0x005D
#define CRAWLING_DRAGON                             0x005E
#define CRASS_CLOWN                                 0x005F
#define ARMORED_ZOMBIE                              0x0060
#define DRAGON_ZOMBIE                               0x0061
#define CLOWN_ZOMBIE                                0x0062
#define PUMPKING_THE_KING_OF_GHOSTS                 0x0063
#define BATTLE_WARRIOR                              0x0064
#define WINGS_OF_WICKED_FLAME                       0x0065
#define MASK_OF_DARKNESS                            0x0066
#define BARON_OF_THE_FIEND_SWORD                    0x0067
#define CURTAIN_OF_THE_DARK_ONES                    0x0068
#define TOMOZAURUS                                  0x0069
#define SPIRIT_OF_THE_WINDS                         0x006A
#define SHINING_ABYSS                               0x006B
#define HEADLESS_KNIGHT                             0x006C
#define GODDESS_WITH_THE_THIRD_EYE                  0x006D
#define RUKLAMBA_THE_SPIRIT_KING                    0x006E
#define DOMA_THE_ANGEL_OF_SILENCE                   0x006F
#define KELDO                                       0x0070
#define SOLDIER_ARI                                 0x0071
#define WHITE_MAGICAL_HAT                           0x0072
#define GEARFRIED_THE_IRON_KNIGHT                   0x0073
#define NIGHTMARE_SCORPION                          0x0074
#define SPIRIT_OF_THE_BOOKS                         0x0075
#define XYZ_DRAGON_CANNON                           0x0076
#define HUMANOID_SLIME                              0x0077
#define DREAM_CLOWN                                 0x0078
#define SLEEPING_LION                               0x0079
#define YAMATANO_DRAGON_SCROLL                      0x007A
#define DARK_PLANT                                  0x007B
#define WORM_DRAKE                                  0x007C
#define FAITH_BIRD                                  0x007D
#define ORION_THE_BATTLE_KING                       0x007E
#define ANSATSU                                     0x007F
#define LAMOON                                      0x0080
#define NEMURIKO                                    0x0081
#define WEATHER_CONTROL                             0x0082
#define OCTOBERSER                                  0x0083
#define HUMANOID_WORM_DRAKE                         0x0084
#define CHARUBIN_THE_FIRE_KNIGHT                    0x0085
#define REVIVAL_JAM                                 0x0086
#define FIENDS_HAND                                 0x0087
#define WITTY_PHANTOM                               0x0088
#define BUSTER_BLADER                               0x0089
#define DARK_NECROFEAR                              0x008A
#define BLUE_EYED_SILVER_ZOMBIE                     0x008B
#define TOAD_MASTER                                 0x008C
#define SPIKED_SNAIL                                0x008D
#define FLAME_MANIPULATOR                           0x008E
#define NECROLANCER_THE_TIMELORD                    0x008F
#define DJINN_THE_WATCHER_OF_THE_WIND               0x0090
#define THE_BEWITCHING_PHANTOM_THIEF                0x0091
#define TEMPLE_OF_SKULLS                            0x0092
#define MONSTER_EGG                                 0x0093
#define THE_SHADOW_WHO_CONTROLS_THE_DARK            0x0094
#define X_HEAD_CANNON                               0x0095
#define AKIHIRON                                    0x0096
#define ORGOTH_THE_RELENTLESS                       0x0097
#define THE_MELTING_RED_SHADOW                      0x0098
#define DOKUROIZO_THE_GRIM_REAPER                   0x0099
#define FIRE_REAPER                                 0x009A
#define LARVAS                                      0x009B
#define HARD_ARMOR                                  0x009C
#define FIREGRASS                                   0x009D
#define CYBER_JAR                                   0x009E
#define DIG_BEAK                                    0x009F
#define M_WARRIOR_1                                 0x00A0
#define M_WARRIOR_2                                 0x00A1
#define BANISHER_OF_THE_LIGHT                       0x00A2
#define LISARK                                      0x00A3
#define DES_FERAL_IMP                               0x00A4
#define THE_JUDGEMENT_HAND                          0x00A5
#define MYSTERIOUS_PUPPETEER                        0x00A6
#define ANCIENT_JAR                                 0x00A7
#define DARKFIRE_DRAGON                             0x00A8
#define DARK_KING_OF_THE_ABYSS                      0x00A9
#define SPIRIT_OF_THE_HARP                          0x00AA
#define BIG_EYE                                     0x00AB
#define ARMAILL                                     0x00AC
#define GIANT_RAT                                   0x00AD
#define SENJU_OF_THE_THOUSAND_HANDS                 0x00AE
#define UFO_TURTLE                                  0x00AF
#define FIRE_EYE                                    0x00B0
#define MONSTURTLE                                  0x00B1
#define CLAW_REACHER                                0x00B2
#define PHANTOM_DEWAN                               0x00B3
#define ARLOWNAY                                    0x00B4
#define FLASH_ASSAILANT                             0x00B5
#define KARATE_MAN                                  0x00B6
#define LUCKY_TRINKET                               0x00B7
#define GENIN                                       0x00B8
#define DARK_ZEBRA                                  0x00B9
#define FIEND_REFLECTION_2                          0x00BA
#define GATE_DEEG                                   0x00BB
#define GIANT_GERM                                  0x00BC
#define FUSIONIST                                   0x00BD
#define NIMBLE_MOMONGA                              0x00BE
#define LALA_LI_OON                                 0x00BF
#define KEY_MACE                                    0x00C0
#define FINAL_DESTINY                               0x00C1
#define HEAVY_STORM                                 0x00C2
#define DORON                                       0x00C3
#define CYCLON_LASER                                0x00C4
#define BOAR_SOLDIER                                0x00C5
#define HAPPY_LOVER                                 0x00C6
#define PENGUIN_KNIGHT                              0x00C7
#define PETIT_DRAGON                                0x00C8
#define FRENZIED_PANDA                              0x00C9
#define AIR_MARMOT_OF_NEFARIOUSNESS                 0x00CA
#define PHANTOM_GHOST                               0x00CB
#define MOTHER_GRIZZLY                              0x00CC
#define FLYING_KAMAKIRI_1                           0x00CD
#define TWIN_LONG_RODS_1                            0x00CE
#define DROLL_BIRD                                  0x00CF
#define PETIT_ANGEL                                 0x00D0
#define WINGED_CLEAVER                              0x00D1
#define HINOTAMA_SOUL                               0x00D2
#define KAMINARIKOZOU                               0x00D3
#define MEOTOKO                                     0x00D4
#define AQUA_MADOOR                                 0x00D5
#define KAGEMUSHA_OF_THE_BLUE_FLAME                 0x00D6
#define FLAME_GHOST                                 0x00D7
#define NIGHTMARE_PENGUIN                           0x00D8
#define B_SKULL_DRAGON                              0x00D9
#define TWO_MOUTH_DARKRULER                         0x00DA
#define SOLITUDE                                    0x00DB
#define MASKED_SORCERER                             0x00DC
#define KUMOOTOKO                                   0x00DD
#define CEREMONIAL_BELL                             0x00DE
#define ROARING_OCEAN_SNAKE                         0x00DF
#define TRAP_MASTER                                 0x00E0
#define FIEND_SWORD                                 0x00E1
#define SONIC_BIRD                                  0x00E2
#define MYSTIC_TOMATO                               0x00E3
#define WOOD_REMAINS                                0x00E4
#define HOURGLASS_OF_LIFE                           0x00E5
#define RARE_FISH                                   0x00E6
#define WOOD_CLOWN                                  0x00E7
#define KOTODAMA                                    0x00E8
#define JAM_BREEDING_MACHINE                        0x00E9
#define OBELISK_THE_TORMENTOR                       0x00EA
#define WODAN_THE_RESIDENT_OF_THE_FOREST            0x00EB
#define PERFECT_MACHINE_KING                        0x00EC
#define HANIWA                                      0x00ED
#define SLIFER_THE_SKY_DRAGON                       0x00EE
#define VISHWAR_RANDI                               0x00EF
#define THE_WINGED_DRAGON_OF_RA_BATTLE_MODE         0x00F0
#define DARK_ASSAILANT                              0x00F1
#define CANDLE_OF_FATE                              0x00F2
#define WATER_ELEMENT                               0x00F3
#define DISSOLVEROCK                                0x00F4
#define FLYING_FISH                                 0x00F5
#define ONE_WHO_HUNTS_SOULS                         0x00F6
#define ROOT_WATER                                  0x00F7
#define AMPHIBIAN_BEAST                             0x00F8
#define WATER_OMOTICS                               0x00F9
#define ALLIGATORS_SWORD_DRAGON                     0x00FA
#define ENCHANTING_MERMAID                          0x00FB
#define NEKOGAL_1                                   0x00FC
#define ROCKET_WARRIOR                              0x00FD
#define AQUA_SERPENT                                0x00FE
#define PREVENT_RAT                                 0x00FF
#define DIMENSIONAL_WARRIOR                         0x0100
#define THE_LEGENDARY_FISHERMAN                     0x0101
#define BEASTKING_OF_THE_SWAMPS                     0x0102
#define SATELLITE_CANNON                            0x0103
#define LUNAR_QUEEN_ELZAIM                          0x0104
#define WICKED_MIRROR                               0x0105
#define THE_LITTLE_SWORDSMAN_OF_AILE                0x0106
#define ROCK_OGRE_GROTTO_2                          0x0107
#define WING_EGG_ELF                                0x0108
#define THE_FURIOUS_SEA_KING                        0x0109
#define PRINCESS_OF_TSURUGI                         0x010A
#define MORPHING_JAR_2                              0x010B
#define VORSE_RAIDER                                0x010C
#define VERSAGO_THE_DESTROYER                       0x010D
#define WETHA                                       0x010E
#define MEGIRUS_LIGHT                               0x010F
#define MAVELUS                                     0x0110
#define ANCIENT_TREE_OF_ENLIGHTENMENT               0x0111
#define GREEN_PHANTOM_KING                          0x0112
#define GROUND_ATTACKER_BUGROTH                     0x0113
#define RAY_TEMPERATURE                             0x0114
#define FLAME_CHAMPION                              0x0115
#define PETIT_MOTH                                  0x0116
#define TWIN_HEADED_FIRE_DRAGON                     0x0117
#define DARKFIRE_SOLDIER_1                          0x0118
#define MYSTIC_CLOWN                                0x0119
#define MYSTICAL_SHEEP_2                            0x011A
#define HOLOGRAH                                    0x011B
#define TAO_THE_CHANTER                             0x011C
#define SERPENT_MARAUDER                            0x011D
#define MR_VOLCANO                                  0x011E
#define OGRE_OF_THE_BLACK_SHADOW                    0x011F
#define DARKFIRE_SOLDIER_2                          0x0120
#define CHANGE_SLIME                                0x0121
#define MOON_ENVOY                                  0x0122
#define FIREYAROU                                   0x0123
#define KISEITAI                                    0x0124
#define MASAKI_THE_LEGENDARY_SWORDSMAN              0x0125
#define DRAGONESS_THE_WICKED_KNIGHT                 0x0126
#define CYBER_FALCON                                0x0127
#define ONE_EYED_SHIELD_DRAGON                      0x0128
#define THE_WINGED_DRAGON_OF_RA_SPHERE_MODE         0x0129
#define WICKED_DRAGON_WITH_THE_ERSATZ_HEAD          0x012A
#define SONIC_MAID                                  0x012B
#define KURAMA                                      0x012C
#define LEGENDARY_SWORD                             0x012D
#define SWORD_OF_DARK_DESTRUCTION                   0x012E
#define DARK_ENERGY                                 0x012F
#define AXE_OF_DESPAIR                              0x0130
#define LASER_CANNON_ARMOR                          0x0131
#define INSECT_ARMOR_WITH_LASER_CANNON              0x0132
#define ELFS_LIGHT                                  0x0133
#define BEAST_FANGS                                 0x0134
#define STEEL_SHELL                                 0x0135
#define VILE_GERMS                                  0x0136
#define BLACK_PENDANT                               0x0137
#define SILVER_BOW_AND_ARROW                        0x0138
#define HORN_OF_LIGHT                               0x0139
#define HORN_OF_THE_UNICORN                         0x013A
#define DRAGON_TREASURE                             0x013B
#define ELECTRO_WHIP                                0x013C
#define CYBER_SHIELD                                0x013D
#define ELEGANT_EGOTIST                             0x013E
#define MYSTICAL_MOON                               0x013F
#define STOP_DEFENSE                                0x0140
#define MALEVOLENT_NUZZLER                          0x0141
#define VIOLET_CRYSTAL                              0x0142
#define BOOK_OF_SECRET_ARTS                         0x0143
#define INVIGORATION                                0x0144
#define MACHINE_CONVERSION_FACTORY                  0x0145
#define RAISE_BODY_HEAT                             0x0146
#define FOLLOW_WIND                                 0x0147
#define POWER_OF_KAISHIN                            0x0148
#define DRAGON_CAPTURE_JAR                          0x0149
#define FOREST                                      0x014A
#define WASTELAND                                   0x014B
#define MOUNTAIN                                    0x014C
#define SOGEN                                       0x014D
#define UMI                                         0x014E
#define YAMI                                        0x014F
#define DARK_HOLE                                   0x0150
#define RAIGEKI                                     0x0151
#define MOOYAN_CURRY                                0x0152
#define RED_MEDICINE                                0x0153
#define GOBLINS_SECRET_REMEDY                       0x0154
#define SOUL_OF_THE_PURE                            0x0155
#define DIAN_KETO_THE_CURE_MASTER                   0x0156
#define SPARKS                                      0x0157
#define HINOTAMA                                    0x0158
#define FINAL_FLAME                                 0x0159
#define OOKAZI                                      0x015A
#define TREMENDOUS_FIRE                             0x015B
#define SWORDS_OF_REVEALING_LIGHT                   0x015C
#define SPELLBINDING_CIRCLE                         0x015D
#define DARK_PIERCING_LIGHT                         0x015E
#define YARANZO                                     0x015F
#define KANAN_THE_SWORDMISTRESS                     0x0160
#define TAKRIMINOS                                  0x0161
#define STUFFED_ANIMAL                              0x0162
#define MEGASONIC_EYE                               0x0163
#define SUPER_WAR_LION                              0x0164
#define YAMADRON                                    0x0165
#define SEIYARYU                                    0x0166
#define THREE_LEGGED_ZOMBIES                        0x0167
#define ZERA_THE_MANT                               0x0168
#define FLYING_PENGUIN                              0x0169
#define MILLENNIUM_SHIELD                           0x016A
#define FAIRYS_GIFT                                 0x016B
#define BLACK_LUSTER_SOLDIER                        0x016C
#define FIENDS_MIRROR                               0x016D
#define LABYRINTH_WALL                              0x016E
#define JIRAI_GUMO                                  0x016F
#define SHADOW_GHOUL                                0x0170
#define WALL_SHADOW                                 0x0171
#define LABYRINTH_TANK                              0x0172
#define SANGA_OF_THE_THUNDER                        0x0173
#define KAZEJIN                                     0x0174
#define SUIJIN                                      0x0175
#define GATE_GUARDIAN                               0x0176
#define DUNGEON_WORM                                0x0177
#define MONSTER_TAMER                               0x0178
#define RYU_KISHIN_POWERED                          0x0179
#define SWORDSTALKER                                0x017A
#define LA_JINN_THE_MYSTICAL_GENIE_OF_THE_LAMP      0x017B
#define BLUE_EYES_ULTIMATE_DRAGON                   0x017C
#define TOON_ALLIGATOR                              0x017D
#define RUDE_KAISER                                 0x017E
#define PARROT_DRAGON                               0x017F
#define DARK_RABBIT                                 0x0180
#define BICKURIBOX                                  0x0181
#define HARPIES_PET_DRAGON                          0x0182
#define MYSTIC_LAMP                                 0x0183
#define PENDULUM_MACHINE                            0x0184
#define GILTIA_THE_D_KNIGHT                         0x0185
#define LAUNCHER_SPIDER                             0x0186
#define ZOA                                         0x0187
#define METALZOA                                    0x0188
#define ZONE_EATER                                  0x0189
#define STEEL_SCORPION                              0x018A
#define DANCING_ELF                                 0x018B
#define OCUBEAM                                     0x018C
#define LEGHUL                                      0x018D
#define OOGUCHI                                     0x018E
#define GAMMA_THE_MAGNET_WARRIOR                    0x018F
#define EMPEROR_OF_THE_LAND_AND_SEA                 0x0190
#define USHI_ONI                                    0x0191
#define MONSTER_EYE                                 0x0192
#define LEOGUN                                      0x0193
#define TATSUNOOTOSHIGO                             0x0194
#define SABER_SLASHER                               0x0195
#define KAISER_SEA_HORSE                            0x0196
#define MACHINE_KING                                0x0197
#define GIANT_MECH_SOLDIER                          0x0198
#define METAL_DRAGON                                0x0199
#define MECHANICAL_SPIDER                           0x019A
#define BAT                                         0x019B
#define THE_WINGED_DRAGON_OF_RA_PHOENIX_MODE        0x019C
#define CYBER_SOLDIER                               0x019D
#define SHOVEL_CRUSHER                              0x019E
#define MECHANICALCHASER                            0x019F
#define BLOCKER                                     0x01A0
#define BLAST_JUGGLER                               0x01A1
#define GOLGOIL                                     0x01A2
#define FLYING_KAMAKIRI_2                           0x01A3
#define CYBER_STEIN                                 0x01A4
#define CYBER_COMMANDER                             0x01A5
#define JINZO_7                                     0x01A6
#define DICE_ARMADILLO                              0x01A7
#define SKY_DRAGON                                  0x01A8
#define THUNDER_DRAGON                              0x01A9
#define STONE_D_                                    0x01AA
#define KAISER_DRAGON                               0x01AB
#define MAGICIAN_OF_FAITH                           0x01AC
#define GODDESS_OF_WHIM                             0x01AD
#define GRADIUS                                     0x01AE
#define ICE_WATER                                   0x01AF
#define WATERDRAGON_FAIRY                           0x01B0
#define ANCIENT_ELF                                 0x01B1
#define HARPIES_BROTHER                             0x01B2
#define AERIS                                       0x01B3
#define WHITE_DOLPHIN                               0x01B4
#define DEEPSEA_SHARK                               0x01B5
#define METAL_FISH                                  0x01B6
#define GRAND_TIKI_ELDER                            0x01B7
#define SEVEN_COLORED_FISH                          0x01B8
#define MECH_BASS                                   0x01B9
#define AQUA_DRAGON                                 0x01BA
#define SEA_KING_DRAGON                             0x01BB
#define TURU_PURUN                                  0x01BC
#define GIANT_REX                                   0x01BD
#define AQUA_SNAKE                                  0x01BE
#define GIANT_RED_SEASNAKE                          0x01BF
#define SPIKE_SEADRA                                0x01C0
#define THIRTY_THOUSAND_YEAR_WHITE_TURTLE           0x01C1
#define KAPPA_AVENGER                               0x01C2
#define KANIKABUTO                                  0x01C3
#define ZARIGUN                                     0x01C4
#define MILLENNIUM_GOLEM                            0x01C5
#define DESTROYER_GOLEM                             0x01C6
#define BARREL_ROCK                                 0x01C7
#define MINOMUSHI_WARRIOR                           0x01C8
#define THE_MASKED_BEAST                            0x01C9
#define KAMINARI_ATTACK                             0x01CA
#define TRIPWIRE_BEAST                              0x01CB
#define BOLT_ESCARGOT                               0x01CC
#define BOLT_PENGUIN                                0x01CD
#define THE_IMMORTAL_OF_THUNDER                     0x01CE
#define ELECTRIC_SNAKE                              0x01CF
#define WING_EAGLE                                  0x01D0
#define PUNISHED_EAGLE                              0x01D1
#define SKULL_RED_BIRD                              0x01D2
#define CRIMSON_SUNBIRD                             0x01D3
#define QUEEN_BIRD                                  0x01D4
#define ARMED_NINJA                                 0x01D5
#define MAGICAL_GHOST                               0x01D6
#define SOUL_HUNTER                                 0x01D7
#define THE_EARL_OF_DEMISE                          0x01D8
#define VERMILLION_SPARROW                          0x01D9
#define SEA_KAMEN                                   0x01DA
#define SINISTER_SERPENT                            0x01DB
#define GANIGUMO                                    0x01DC
#define ALINSECTION                                 0x01DD
#define INSECT_SOLDIERS_OF_THE_SKY                  0x01DE
#define COCKROACH_KNIGHT                            0x01DF
#define KUWAGATA_A                                  0x01E0
#define BURGLAR                                     0x01E1
#define PRAGTICAL                                   0x01E2
#define GARVAS                                      0x01E3
#define AMEBA                                       0x01E4
#define KOROGASHI                                   0x01E5
#define BOO_KOO                                     0x01E6
#define FLOWER_WOLF                                 0x01E7
#define RAINBOW_FLOWER                              0x01E8
#define BARREL_LILY                                 0x01E9
#define NEEDLE_BALL                                 0x01EA
#define PEACOCK                                     0x01EB
#define HOSHININGEN                                 0x01EC
#define MAHA_VAILO                                  0x01ED
#define RAINBOW_MARINE_MERMAID                      0x01EE
#define MUSICIAN_KING                               0x01EF
#define WILMEE                                      0x01F0
#define YADO_KARU                                   0x01F1
#define MORINPHEN                                   0x01F2
#define BONEHEIMER                                  0x01F3
#define DRAGON_SEEKER                               0x01F4
#define MAN_EATER_BUG                               0x01F5
#define PENGUIN_TORPEDO                             0x01F6
#define TURTLE_RACCOON                              0x01F7
#define FLAME_DANCER                                0x01F8
#define PRISMAN                                     0x01F9
#define GALE_DOGRA                                  0x01FA
#define CRAZY_FISH                                  0x01FB
#define CYBER_SAURUS                                0x01FC
#define BRACCHIO_RAIDUS                             0x01FD
#define LAUGHING_FLOWER                             0x01FE
#define BEAN_SOLDIER                                0x01FF
#define CANNON_SOLDIER                              0x0200
#define GUARDIAN_OF_THE_THRONE_ROOM                 0x0201
#define ASURA_PRIEST                                0x0202
#define THE_STATUE_OF_EASTER_ISLAND                 0x0203
#define MUKA_MUKA                                   0x0204
#define ZOMBYRA_THE_DARK                            0x0205
#define BOULDER_TORTOISE                            0x0206
#define FIRE_KRAKEN                                 0x0207
#define TURTLE_BIRD                                 0x0208
#define SKULLBIRD                                   0x0209
#define MONSTROUS_BIRD                              0x020A
#define THE_BISTRO_BUTCHER                          0x020B
#define STAR_BOY                                    0x020C
#define SPIRIT_OF_THE_MOUNTAIN                      0x020D
#define EARTHBOUND_SPIRIT                           0x020E
#define MILUS_RADIANT                               0x020F
#define TOGEX                                       0x0210
#define FLAME_CEREBRUS                              0x0211
#define EMBODIMENT_OF_APOPHIS                       0x0212
#define MYSTICAL_SAND                               0x0213
#define GEMINI_ELF                                  0x0214
#define KWAGAR_HERCULES                             0x0215
#define MINAR                                       0x0216
#define ANCIENT_LAMP                                0x0217
#define MECHALEON                                   0x0218
#define MEGA_THUNDERBALL                            0x0219
#define NIWATORI                                    0x021A
#define AMAZON_CHAIN_MASTER                         0x021B
#define SKELENGEL                                   0x021C
#define HANE_HANE                                   0x021D
#define MISAIRUZAME                                 0x021E
#define THUNDER_NYAN_NYAN                           0x021F
#define DHARMA_CANNON                               0x0220
#define SKELGON                                     0x0221
#define WOW_WARRIOR                                 0x0222
#define GRIGGLE                                     0x0223
#define BONE_MOUSE                                  0x0224
#define FROG_THE_JAM                                0x0225
#define LAST_TUSK_MAMMOTH                           0x0226
#define DARK_ELF                                    0x0227
#define WINGED_DRAGON_GUARDIAN_OF_THE_FORTRESS_2    0x0228
#define MUSHROOM_MAN_2                              0x0229
#define LAVA_BATTLEGUARD                            0x022A
#define QUEENS_KNIGHT                               0x022B
#define INJECTION_FAIRY_LILY                        0x022C
#define JACKS_KNIGHT                                0x022D
#define POT_THE_TRICK                               0x022E
#define OSCILLO_HERO                                0x022F
#define INVADER_FROM_ANOTHER_DIMENSION              0x0230
#define LESSER_DRAGON                               0x0231
#define NEEDLE_WORM                                 0x0232
#define KINGS_KNIGHT                                0x0233
#define GREAT_MAMMOTH_OF_GOLDFINE                   0x0234
#define GIL_GARTH                                   0x0235
#define YORMUNGARDE                                 0x0236
#define DARKWORLD_THORNS                            0x0237
#define BLADE_KNIGHT                                0x0238
#define GERNIA                                      0x0239
#define TRAKADON                                    0x023A
#define B_DRAGON_JUNGLE_KING                        0x023B
#define EMPRESS_JUDGE                               0x023C
#define LITTLE_D                                    0x023D
#define WITCH_OF_THE_BLACK_FOREST                   0x023E
#define Y_DRAGON_HEAD                               0x023F
#define GIANT_SCORPION_OF_THE_TUNDRA                0x0240
#define CROW_GOBLIN                                 0x0241
#define DARK_MAGICIAN_KNIGHT                        0x0242
#define ABYSS_FLOWER                                0x0243
#define PATROL_ROBO                                 0x0244
#define TAKUHEE                                     0x0245
#define DARK_WITCH                                  0x0246
#define DESTINY_BOARD                               0x0247
#define SPIRIT_MESSAGE_I                            0x0248
#define SPIRIT_MESSAGE_N                            0x0249
#define SPIRIT_MESSAGE_A                            0x024A
#define SPIRIT_MESSAGE_L                            0x024B
#define LIVING_VASE                                 0x024C
#define TENTACLE_PLANT                              0x024D
#define Z_METAL_TANK                                0x024E
#define MORPHING_JAR                                0x024F
#define MUSE_A                                      0x0250
#define XY_DRAGON_CANNON                            0x0251
#define ROSE_SPECTRE_OF_DUNN                        0x0252
#define FIEND_REFLECTION_1                          0x0253
#define XZ_TANK_CANNON                              0x0254
#define YZ_TANK_DRAGON                              0x0255
#define LITTLE_CHIMERA                              0x0256
#define VIOLENT_RAIN                                0x0257
#define EXODIA_NECROSS                              0x0258
#define MONSTER_REBORN                              0x0259
#define PENGUIN_SOLDIER                             0x025A
#define FAIRY_DRAGON                                0x025B
#define HELPOEMER                                   0x025C
#define LAVA_GOLEM                                  0x025D
#define NEWDORIA                                    0x025E
#define DARK_JEROID                                 0x025F
#define SHINING_FRIENDSHIP                          0x0260
#define GRAVEDIGGER_GHOUL                           0x0261
#define ELECTRIC_LIZARD                             0x0262
#define HIROS_SHADOW_SCOUT                          0x0263
#define LADY_OF_FAITH                               0x0264
#define TWIN_HEADED_THUNDER_DRAGON                  0x0265
#define HUNTER_SPIDER                               0x0266
#define ARMORED_STARFISH                            0x0267
#define EXECUTOR_MAKYURA                            0x0268
#define MARINE_BEAST                                0x0269
#define WARRIOR_OF_TRADITION                        0x026A
#define BYSER_SHOCK                                 0x026B
#define SNAKEYASHI                                  0x026C
#define SUCCUBUS_KNIGHT                             0x026D
#define ILL_WITCH                                   0x026E
#define VISER_DES                                   0x026F
#define HIGH_TIDE_GYOJIN                            0x0270
#define FAIRY_OF_THE_FOUNTAIN                       0x0271
#define AMAZON_OF_THE_SEAS                          0x0272
#define NEKOGAL_2                                   0x0273
#define WITCHS_APPRENTICE                           0x0274
#define PUPPET_MASTER                               0x0275
#define AMAZON_FIGHTER                              0x0276
#define MAIDEN_OF_THE_MOONLIGHT                     0x0277
#define STONE_OGRE_GROTTO                           0x0278
#define AMAZON_SWORD_WOMAN                          0x0279
#define VAMPIRE_LORD                                0x027A
#define QUEENS_DOUBLE                               0x027B
#define DARK_PALADIN                                0x027C
#define TRENT                                       0x027D
#define QUEEN_OF_AUTUMN_LEAVES                      0x027E
#define AMPHIBIOUS_BUGROTH                          0x027F
#define DIFFERENT_DIMENSION_DRAGON                  0x0280
#define AMAZON_ARCHERS                              0x0281
#define MYSTICAL_SHEEP_1                            0x0282
#define YAMATA_DRAGON                               0x0283
#define SHINATO_KING_OF_A_HIGHER_PLANE              0x0284
#define DARK_FLARE_KNIGHT                           0x0285
#define MIRAGE_KNIGHT                               0x0286
#define BERSERK_DRAGON                              0x0287
#define MACHINE_ATTACKER                            0x0288
#define COMMAND_ANGEL                               0x0289
#define WHIPTAIL_CROW                               0x028A
#define KUNAI_WITH_CHAIN                            0x028B
#define MAGICAL_LABYRINTH                           0x028C
#define WARRIOR_ELIMINATION                         0x028D
#define SALAMANDRA                                  0x028E
#define CURSEBREAKER                                0x028F
#define ETERNAL_REST                                0x0290
#define MEGAMORPH                                   0x0291
#define METALMORPH                                  0x0292
#define WINGED_TRUMPETER                            0x0293
#define STAIN_STORM                                 0x0294
#define CRUSH_CARD                                  0x0295
#define ERADICATING_AEROSOL                         0x0296
#define BREATH_OF_LIGHT                             0x0297
#define ETERNAL_DROUGHT                             0x0298
#define DES_VOLSTGALPH                              0x0299
#define TOON_DARK_MAGICIAN_GIRL                     0x029A
#define GILFORD_THE_LIGHTNING                       0x029B
#define BRIGHT_CASTLE                               0x029C
#define SHADOW_SPELL                                0x029D
#define BLACK_LUSTER_RITUAL                         0x029E
#define MYSTICAL_BEAST_SERKET                       0x029F
#define HARPIES_FEATHER_DUSTER                      0x02A0
#define CYBER_HARPIE                                0x02A1
#define LIGHTNING_CONGER                            0x02A2
#define EXARION_UNIVERSE                            0x02A3
#define LEGENDARY_FIEND                             0x02A4
#define GADGET_SOLDIER                              0x02A5
#define MELCHID_THE_FOUR_FACE_BEAST                 0x02A6
#define NUVIA_THE_WICKED                            0x02A7
#define MASKED_BEAST_DES_GARDIUS                    0x02A8
#define HOUSE_OF_ADHESIVE_TAPE                      0x02A9
#define EATGABOON                                   0x02AA
#define BEAR_TRAP                                   0x02AB
#define INVISIBLE_WIRE                              0x02AC
#define ACID_TRAP_HOLE                              0x02AD
#define WIDESPREAD_RUIN                             0x02AE
#define GOBLIN_FAN                                  0x02AF
#define BAD_REACTION_TO_SIMOCHI                     0x02B0
#define REVERSE_TRAP                                0x02B1
#define FAKE_TRAP                                   0x02B2
#define VALKYRION_THE_MAGNA_WARRIOR                 0x02B3
#define TORRENTIAL_TRIBUTE                          0x02B4
#define BECKON_TO_DARKNESS                          0x02B5
#define INFINITE_DISMISSAL                          0x02B6
#define SEVEN_COMPLETED                             0x02B7
#define DARK_SAGE                                   0x02B8
#define F_G_D                                       0x02B9
#define MASTER_OF_DRAGON_SOLDIER                    0x02BA
#define MESSENGER_OF_PEACE                          0x02BB
#define DARKNESS_APPROACHES                         0x02BC
#define PERFORMANCE_OF_SWORD                        0x02BD
#define HUNGRY_BURGER                               0x02BE
#define SENGENJIN                                   0x02BF
#define SKULL_GUARDIAN                              0x02C0
#define TRI_HORNED_DRAGON                           0x02C1
#define SERPENT_NIGHT_DRAGON                        0x02C2
#define SKULL_KNIGHT                                0x02C3
#define COSMO_QUEEN                                 0x02C4
#define CHAKRA                                      0x02C5
#define CRAB_TURTLE                                 0x02C6
#define MIKAZUKINOYAIBA                             0x02C7
#define METEOR_DRAGON                               0x02C8
#define METEOR_B_DRAGON                             0x02C9
#define FIREWING_PEGASUS                            0x02CA
#define PSYCHO_PUPPET                               0x02CB
#define GARMA_SWORD                                 0x02CC
#define JAVELIN_BEETLE                              0x02CD
#define FORTRESS_WHALE                              0x02CE
#define DOKURORIDER                                 0x02CF
#define MASK_OF_SHINE_DARK                          0x02D0
#define MAGICIAN_OF_BLACK_CHAOS                     0x02D1
#define DARK_MAGIC_RITUAL                           0x02D2
#define SLOT_MACHINE                                0x02D3
#define SPACE_MEGATRON                              0x02D4
#define RED_ARCHERY_GIRL                            0x02D5
#define RYU_RAN                                     0x02D6
#define MANGA_RYU_RAN                               0x02D7
#define TOON_MERMAID                                0x02D8
#define TOON_SUMMONED_SKULL                         0x02D9
#define DARK_EYES_ILLUSIONIST                       0x02DA
#define RELINQUISHED                                0x02DB
#define JIGEN_BAKUDAN                               0x02DC
#define THOUSAND_EYES_IDOL                          0x02DD
#define THOUSAND_EYES_RESTRICT                      0x02DE
#define STEEL_OGRE_GROTTO_2                         0x02DF
#define BLAST_SPHERE                                0x02E0
#define HYOZANRYU                                   0x02E1
#define ALPHA_THE_MAGNET_WARRIOR                    0x02E2
#define LEGION_THE_FIEND_JESTER                     0x02E3
#define INVITATION_TO_A_DARK_SLEEP                  0x02E4
#define LORD_OF_D                                   0x02E5
#define RED_EYES_BLACK_METAL_DRAGON                 0x02E6
#define BARREL_DRAGON                               0x02E7
#define HANNIBAL_NECROMANCER                        0x02E8
#define PANTHER_WARRIOR                             0x02E9
#define THREE_HEADED_GEEDO                          0x02EA
#define GAZELLE_THE_KING_OF_MYTHICAL_BEASTS         0x02EB
#define STONE_STATUE_OF_THE_AZTECS                  0x02EC
#define BERFOMET                                    0x02ED
#define CHIMERA_THE_FLYING_MYTHICAL_BEAST           0x02EE
#define GEAR_GOLEM_THE_MOVING_FORTRESS              0x02EF
#define JINZO                                       0x02F0
#define SWORDSMAN_OF_LANDSTAR                       0x02F1
#define CYBER_RAIDER                                0x02F2
#define THE_FIEND_MEGACYBER                         0x02F3
#define REFLECT_BOUNDER                             0x02F4
#define BETA_THE_MAGNET_WARRIOR                     0x02F5
#define BIG_SHIELD_GARDNA                           0x02F6
#define DOLL_OF_DEMISE                              0x02F7
#define DARK_MAGICIAN_GIRL                          0x02F8
#define ALLIGATORS_SWORD                            0x02F9
#define INSECT_QUEEN                                0x02FA
#define PARASITE_PARACIDE                           0x02FB
#define SKULL_MARK_LADY_BUG                         0x02FC
#define TINY_GUARDIAN                               0x02FD
#define PINCH_HOPPER                                0x02FE
#define BLUE_EYES_TOON_DRAGON                       0x02FF
#define THE_UNHAPPY_MAIDEN                          0x0300
#define WALL_OF_ILLUSION                            0x0301
#define NEO_THE_MAGIC_SWORDSMAN                     0x0302
#define MAN_EATING_TREASURE_CHEST                   0x0303
#define CHIRON_THE_MAGE                             0x0304
#define SWORD_HUNTER                                0x0305
#define DRILL_BUG                                   0x0306
#define DEEPSEA_WARRIOR                             0x0307
#define BITE_SHOES                                  0x0308
#define SPIKEBOT                                    0x0309
#define BEAST_OF_GILFER                             0x030A
#define THE_PORTRAITS_SECRET                        0x030B
#define THE_GROSS_GHOST_OF_FLED_DREAMS              0x030C
#define BRAIN_CONTROL                               0x030D
#define ANTI_RAIGEKI                                0x030E
#define BLACK_ILLUSION_RITUAL                       0x030F
#define CHANGE_OF_HEART                             0x0310
#define MULTIPLY                                    0x0311
#define EXILE_OF_THE_WICKED                         0x0312
#define LAST_DAY_OF_WITCH                           0x0313
#define RESTRUCTER_REVOLUTION                       0x0314
#define POT_OF_GREED                                0x0315
#define THE_INEXPERIENCED_SPY                       0x0316
#define GATE_SWORD                                  0x0317
#define STEEL_FAN_FIGHTER                           0x0318
#define LEOPARD_GIRL                                0x0319
#define THE_LAST_WARRIOR_FROM_ANOTHER_PLANET        0x031A
#define DUNAMES_DARK_WITCH                          0x031B
#define GARNECIA_ELEFANTIS                          0x031C
#define TOTAL_DEFENSE_SHOGUN                        0x031D
#define BEAST_OF_TALWAR                             0x031E
#define CYBER_TECH_ALLIGATOR                        0x031F
#define TALONS_OF_SHURILANE                         0x0320
#define NUM_CARDS                                   0x0321
#define NUM_TRUE_CARDS                              (NUM_CARDS - 1)

#endif // GUARD_CONSTANTS_CARD_IDS_H
