
enum DuelTextIds
{
  DUEL_TEXT_PLAYER_TURN,             // 08FA15E8;
  DUEL_TEXT_OPPONENT_TURN,           // 08FA165B; // used for non-link duels
  DUEL_TEXT_DUEL_VICTORY,            // 08FA1704;
  DUEL_TEXT_DUEL_LOSS,               // 08FA1776;
  DUEL_TEXT_DUELIST_LEVEL_INCREASED, // 08FA17FA;
  DUEL_TEXT_CARD_OBTAINED,           // 08FA18DA;
  DUEL_TEXT_CAPACITY_INCREASED,      // 08FA1960;
  DUEL_TEXT_CAPACITY_AND_MONEY,      // 08FA1A69; unused?
  DUEL_TEXT_MONEY_OBTAINED,          // 08FA1BD9;
  DUEL_TEXT_ABOUT_DOMINO_OBTAINED,   // 08FA1C84; 
  DUEL_TEXT_ABOUT_MILLION_OBTAINED,  // 08FA1D84; 
  DUEL_TEXT_ABOUT_BILLION_OBTAINED,  // 08FA1EA8; 
  DUEL_TEXT_NO_MONEY_OBTAINED,       // 08FA1FB9; 
  DUEL_TEXT_TOO_MUCH_MONEY,          // 08FA2079; unused?
  DUEL_TEXT_TRANSFORMED_INTO,        // 08FA212D; moths/Cocoon of Evolution
  DUEL_TEXT_SWORDS_REMAIN_EFFECT,    // 08FA21E8;
  DUEL_TEXT_SWORDS_EFFECT_FADED,     // 08FA2320;
  DUEL_TEXT_ALL_EXODIA_PIECES,       // 08FA245B;
  DUEL_TEXT_DESTINY_BOARD_COMPLETE,  // 08FA257B; FINAL message complete
  DUEL_TEXT_OPPONENT_OUT_OF_LP,      // 08FA26A6;
  DUEL_TEXT_PLAYER_OUT_OF_LP,        // 08FA2766;
  DUEL_TEXT_OPPONENT_DECK_OUT,       // 08FA27F7;
  DUEL_TEXT_PLAYER_DECK_OUT,         // 08FA2938;
  DUEL_TEXT_OPPONENT_LINK_TURN,      // 08FA2A43; includes the custom name of the link duel opponent?
  DUEL_TEXT_LINKING,                 // 08FA2AEC;
  DUEL_TEXT_COMMUNICATION_ERROR      // 08FA2B33;
};
