
// Music tracks and sfx each override themselves but not the other.
// Music track titles taken from here: https://downloads.khinsider.com/game-soundtracks/album/yu-gi-oh-reshef-of-destruction-gba

enum MusicIds
{
  // music
  SOUND_NONE = 0x0,                        // None (stops all music)
  MUSIC_TITLE_SCREEN = 0x1,                // Track 1: Title Screen
  MUSIC_2 = 0x2,                           // no effect
  MUSIC_WORLD_MAP = 0x3,                   // Track 2: World Map
  MUSIC_CLOCK_TOWER_SQUARE = 0x4,          // Track 3: Clock Tower Square
  MUSIC_HOME = 0x5,                        // Track 4: Your Home
  MUSIC_GAME_SHOP = 0x6,                   // Track 5: Game Shop
  MUSIC_BACK_ALLEY = 0x7,                  // Track 6: Back Alley
  MUSIC_ISHIZU_ISHTAR = 0x8,               // Track 7: Ishizu Ishtar
  MUSIC_DOMINO_CITY_LIBERATED = 0x9,       // Track 8: Domino City Liberated
  MUSIC_NEO_GHOULS_INVADE = 0xA,           // Track 9: The Neo Ghouls Invade Domino City
  MUSIC_NEO_GHOULS = 0xB,                  // Track 10: The Neo Ghouls
  MUSIC_KAIBACORP = 0xC,                   // Track 11: KaibaCorp
  MUSIC_KAIBALAND = 0xD,                   // Track 12: Kaiba Land
  MUSIC_HOME_2 = 0xE,                      // Track 13: Your Home (2)
  MUSIC_DOMINO_PIER = 0xF,                 // Track 14: Domino Pier
  MUSIC_ITALY = 0x10,                      // Track 15: Italy
  MUSIC_DUNGEON = 0x11,                    // Track 16: Dungeon
  MUSIC_PEGASUS_CASTLE = 0x12,             // Track 17: Pegasus Castle
  MUSIC_INSIDE_PEGASUS_CASTLE = 0x13,      // Track 18: Inside Pegasus Castle
  MUSIC_SOL_CHEVALSKY = 0x14,              // Track 19: Sol Chevalsky
  MUSIC_RESHEF = 0x15,                     // Track 20: Reshef the Dark Being
  MUSIC_RESHEF_DEFEATED = 0x16,            // Track 21: Reshef Defeated
  MUSIC_ESCAPE_FROM_PEGASUS_CASTLE = 0x17, // Track 22: Escape from Pegasus Castle
  MUSIC_ENDING_THEME = 0x18,               // Track 23: Ending Theme
  MUSIC_HALL_OF_ETERNITY = 0x19,           // Track 24: Hall of Eternity
  MUSIC_EGYPT = 0x1A,                      // Track 25: Egypt
  MUSIC_MARIK_ISHTAR = 0x1B,               // Track 26: Marik Ishtar
  MUSIC_BIG_FIVE = 0x1C,                   // Track 27: The Big Five
  MUSIC_29 = 0x1D,                         // no effect
  MUSIC_30 = 0x1E,                         // no effect
  MUSIC_HAPPY_CUTSCENE = 0x1F,             // Track 28: Happy Cutscene
  MUSIC_JEAN_CLAUDE_MAGNUM = 0x20,         // Track 29: Jean Claude Magnum
  MUSIC_MONKEY_ROBOTS = 0x21,              // Track 30: Monkey Robots
  MUSIC_34 = 0x22,                         // no effect
  MUSIC_35 = 0x23,                         // no effect
  MUSIC_36 = 0x24,                         // no effect
  MUSIC_37 = 0x25,                         // no effect
  MUSIC_38 = 0x26,                         // no effect
  MUSIC_39 = 0x27,                         // no effect
  MUSIC_40 = 0x28,                         // no effect
  MUSIC_41 = 0x29,                         // no effect
  MUSIC_42 = 0x2A,                         // no effect
  MUSIC_DUEL_VICTORY = 0x2B,               // Track 31: Duel Victory!
  MUSIC_DUEL_LOSS = 0x2C,                  // Track 32: Lost the Duel...
  MUSIC_DUEL_LOSS_2 = 0x2D,                // Track 33: Lost the Duel... 2 (??)
  MUSIC_NAMING_SCREEN = 0x2E,              // Track 34: Naming Screen
  MUSIC_DECK_ADJUSTMENT_MENU = 0x2F,       // Track 35: Deck Adjustment Menu
  MUSIC_48 = 0x30,                         // no effect
  MUSIC_CREDITS = 0x31,                    // Track 36: Credits
  MUSIC_50 = 0x32,                         // no effect
  MUSIC_51 = 0x33,                         // no effect
  MUSIC_52 = 0x34,                         // no effect
  MUSIC_53 = 0x35,                         // no effect

  // sfx
  SFX_MOVE_CURSOR = 0x36,               //
  SFX_SELECT = 0x37,                    // select option/card
  SFX_CANCEL = 0x38,                    //
  SFX_FORBIDDEN = 0x39,                 //
  SFX_PLACE_CARD = 0x3A,                //
  SFX_DRAW_CARD = 0x3B,                 //
  SFX_FLIP_FACE_UP = 0x3C,              //
  SFX_TRIBUTE = 0x3D,                   //
  SFX_DISCARD = 0x3E,                   //
  MUSIC_63 = 0x3F,                      // no effect
  SFX_MONSTER_EFFECT_ACTIVATION = 0x40, //
  SFX_SPELL_ACTIVATION_START = 0x41,    // before text runs
  SFX_ATTACK_REBUFFED = 0x42,           // slash impact of rebuffed attack (ATK too low to destroy)
  MUSIC_67 = 0x43,                      // no effect
  SFX_ATTACK_EXPLOSION_1 = 0x44,        // explosion from successful attack 1/2 (high)
  SFX_ATTACK_SUCCESSFUL = 0x45,         // slash impact of successful attack (destroyed opp card)
  SFX_ATTACK_EXPLOSION_2 = 0x46,        // explosion from successful attack 2/2 (low)
  SFX_LP_DROP_BLIP = 0x47,              // life points dropping (a single blip)
  MUSIC_72 = 0x48,                      // no effect
  SFX_HEAL_LP = 0x49,                   //
  SFX_BURN_LP = 0x4A,                   //
  SFX_DESTROY_CARD = 0x4B,              // Beckon to Darkness, Final Destiny, etc.
  SFX_SPELL_ACTIVATION_END = 0x4C,      // after text is dismissed
  MUSIC_77 = 0x4D,                      // some kind of duel effect?
  MUSIC_78 = 0x4E,                      // ??
  SFX_FIELD_ACTIVATED = 0x4F,           //
  SFX_IMMOBILISE = 0x50,                //
  MUSIC_81 = 0x51,                      // no effect
  MUSIC_82 = 0x52,                      // ??
  MUSIC_83 = 0x53,                      // ??
  MUSIC_84 = 0x54,                      // ??
  MUSIC_85 = 0x55,                      // ??
  MUSIC_86 = 0x56,                      // one of ra/obeslisk attack
  SFX_SLIFER_ATTACK = 0x57,             // Slifer attack
  MUSIC_88 = 0x58,                      // one of ra/obeslisk attack
  SFX_TRAP_TRIGGERED = 0x59,            //
  SFX_DESTROY_MON_WITH_BACKROW = 0x5A,  //
  MUSIC_91 = 0x5B,                      // no effect
  MUSIC_92 = 0x5C,                      // no effect
  MUSIC_93 = 0x5D,                      // overworld kicking open door?
  MUSIC_94 = 0x5E,                      // overworld shove/punch?
  MUSIC_95 = 0x5F,                      // no effect
  MUSIC_96 = 0x60,                      // no effect
  MUSIC_97 = 0x61,                      // no effect
  MUSIC_98 = 0x62,                      // no effect
  MUSIC_99 = 0x63,                      // no effect
  MUSIC_100 = 0x64,                     // no effect
  MUSIC_101 = 0x65,                     //
  MUSIC_102 = 0x66,                     //
  MUSIC_103 = 0x67,                     //
  MUSIC_104 = 0x68,                     //
  MUSIC_105 = 0x69,                     //
  MUSIC_106 = 0x6A,                     //
  MUSIC_107 = 0x6B,                     // no effect
  MUSIC_108 = 0x6C,                     //
  MUSIC_109 = 0x6D,                     //
  MUSIC_110 = 0x6E,                     //
  MUSIC_111 = 0x6F,                     // no effect
  MUSIC_112 = 0x70,                     //
  MUSIC_113 = 0x71,                     //
  MUSIC_114 = 0x72,                     //
  MUSIC_115 = 0x73,                     //
  MUSIC_116 = 0x74,                     //
  SFX_JOEY_RED_EYES_VOICE = 0x75,                     // Joey voice: something about Red Eyes Black Dragon
  MUSIC_118 = 0x76,                     //
  SFX_KAIBA_BLUE_EYES_VOICE = 0x77,
  MUSIC_120 = 0x78,                     // no effect
  MUSIC_121 = 0x79,                     //
  MUSIC_122 = 0x7A,                     //
  MUSIC_123 = 0x7B,                     //
  MUSIC_124 = 0x7C,                     // Yami Yugi voice: It's my turn
  SFX_ATEM_BLACK_LUSTER_SOLDIER_VOICE = 0x7D,
  MUSIC_126 = 0x7E,                     //
  SFX_YUGI_DARK_MAGICIAN_VOICE = 0x7F,                     //
  MUSIC_128 = 0x80,                     //
  MUSIC_129 = 0x81,                     // no music
  MUSIC_130 = 0x82,                     //
  MUSIC_131 = 0x83,                     //
  MUSIC_132 = 0x84,                     //
  MUSIC_133 = 0x85,                     //
  MUSIC_134 = 0x86,                     // no music
  MUSIC_135 = 0x87,                     //
  MUSIC_136 = 0x88,                     //
  MUSIC_137 = 0x89,                     //
  MUSIC_138 = 0x8A,                     // no music
  MUSIC_139 = 0x8B,                     // no music
  MUSIC_140 = 0x8C,                     // no effect
  MUSIC_141 = 0x8D,                     // no effect
  MUSIC_142 = 0x8E,                     // no effect

  // music
  MUSIC_143 = 0x8F, // Track 37: Ante

  // assorted
  MUSIC_144 = 0x90,                        // no effect
  MUSIC_145 = 0x91,                        // no effect
  MUSIC_146 = 0x92,                        // no effect
  MUSIC_147 = 0x93,                        // no effect
  MUSIC_148 = 0x94,                        //
  MUSIC_149 = 0x95,                        //
  MUSIC_150 = 0x96,                        // no effect
  MUSIC_151 = 0x97,                        //
  MUSIC_152 = 0x98,                        //
  MUSIC_153 = 0x99,                        //
  MUSIC_154 = 0x9A,                        //
  MUSIC_155 = 0x9B,                        //
  MUSIC_156 = 0x9C,                        // no effect
  MUSIC_157 = 0x9D,                        //
  MUSIC_158 = 0x9E,                        //
  MUSIC_159 = 0x9F,                        //
  MUSIC_160 = 0xA0,                        //
  MUSIC_161 = 0xA1,                        //
  MUSIC_162 = 0xA2,                        //
  MUSIC_163 = 0xA3,                        // no effect
  MUSIC_164 = 0xA4,                        //
  MUSIC_165 = 0xA5,                        //
  MUSIC_166 = 0xA6,                        //
  MUSIC_167 = 0xA7,                        //
  MUSIC_168 = 0xA8,                        //
  MUSIC_169 = 0xA9,                        //
  MUSIC_170 = 0xAA,                        //
  MUSIC_171 = 0xAB,                        // no effect
  MUSIC_172 = 0xAC,                        //
  MUSIC_173 = 0xAD,                        //
  MUSIC_174 = 0xAE,                        //
  MUSIC_175 = 0xAF,                        //
  MUSIC_176 = 0xB0,                        // no effect
  MUSIC_177 = 0xB1,                        //
  MUSIC_178 = 0xB2,                        //
  MUSIC_179 = 0xB3,                        //
  MUSIC_180 = 0xB4,                        //
  MUSIC_181 = 0xB5,                        //
  MUSIC_182 = 0xB6,                        //
  MUSIC_183 = 0xB7,                        // no effect
  MUSIC_184 = 0xB8,                        //
  MUSIC_185 = 0xB9,                        //
  MUSIC_186 = 0xBA,                        //
  MUSIC_187 = 0xBB,                        //
  MUSIC_188 = 0xBC,                        // no effect
  MUSIC_189 = 0xBD,                        //
  MUSIC_190 = 0xBE,                        //
  MUSIC_191 = 0xBF,                        //
  MUSIC_192 = 0xC0,                        //
  MUSIC_193 = 0xC1,                        //
  MUSIC_194 = 0xC2,                        // no effect
  MUSIC_195 = 0xC3,                        //
  MUSIC_196 = 0xC4,                        //
  MUSIC_197 = 0xC5,                        //
  MUSIC_198 = 0xC6,                        //
  MUSIC_199 = 0xC7,                        //
  MUSIC_200 = 0xC8,                        // no effect
  SFX_CODE_ENTRY_SUCCESS = 0xC9,           //
  SFX_DIALOGUE = 0xCA,                     // open/close/progress dialogue box
  MUSIC_203 = 0xCB,                        // dog barking?
  MUSIC_204 = 0xCC,                        // no effect
  MUSIC_205 = 0xCD,                        //
  MUSIC_206 = 0xCE,                        //
  MUSIC_207 = 0xCF,                        //
  MUSIC_208 = 0xD0,                        // no effect
  MUSIC_209 = 0xD1,                        // no effect
  SFX_TITLE_SCREEN_SELECT = 0xD2,          // title screen select
  SFX_DUEL_COMPUTER_BEEP = 0xD3,           // duel computer beep
  MUSIC_212 = 0xD4,                        // door handle opening?
  SFX_TRANSITION_OVERWORLD_TO_ANTE = 0xD5, // warp/fade from overworld into ante screen
  MUSIC_214 = 0xD6,                        // no effect
  MUSIC_215 = 0xD7,                        // no effect
  MUSIC_216 = 0xD8,                        // no effect
  MUSIC_217 = 0xD9,                        //
  MUSIC_218 = 0xDA,                        //
  MUSIC_219 = 0xDB,                        //
  MUSIC_220 = 0xDC,                        //
  MUSIC_221 = 0xDD,                        // no effect
  SFX_TRANSITION_TRUNK_TO_DUEL = 0xDE,     // warp/fade from ante into duel
  MUSIC_223 = 0xDF,                        //
  MUSIC_224 = 0xE0,                        //
  MUSIC_225 = 0xE1,                        //
  MUSIC_226 = 0xE2,                        //
  MUSIC_227 = 0xE3,                        // no effect
  MUSIC_228 = 0xE4,                        //
  MUSIC_229 = 0xE5,                        //
  MUSIC_230 = 0xE6,                        //
  MUSIC_231 = 0xE7,                        //
  MUSIC_232 = 0xE8,                        //
  MUSIC_233 = 0xE9,                        // Track ?: quiet background hum?
  MUSIC_234 = 0xEA,                        // Track ?: truck driving/picking up speed?
  MUSIC_235 = 0xEB,                        //
  MUSIC_236 = 0xEC,                        //
  MUSIC_237 = 0xED,                        //
  MUSIC_238 = 0xEE,                        //
  MUSIC_239 = 0xEF,                        // Track ?: waves/seagulls/boat horn?
  MUSIC_240 = 0xF0,                        //
  MUSIC_241 = 0xF1,                        //
  MUSIC_242 = 0xF2,                        //
  MUSIC_243 = 0xF3,                        //
  MUSIC_244 = 0xF4,                        //
  MUSIC_245 = 0xF5,                        //
  MUSIC_246 = 0xF6,                        //
  MUSIC_247 = 0xF7,                        //
  MUSIC_248 = 0xF8,                        //
  MUSIC_249 = 0xF9,                        // Track ?: background hum with birdsound?
  MUSIC_250 = 0xFA,                        // Track ?: Galapagos in cutscene? wind/waves/dolphins but no music?
  MUSIC_251 = 0xFB,                        // Track ?: same as 0xFA but with footsteps
  MUSIC_252 = 0xFC,                        // Track ?: outdoors loud?
  MUSIC_253 = 0xFD,                        // Track ?: outdoors quiet?
  MUSIC_254 = 0xFE,                        // Track ?: outdoors loud?
  MUSIC_255 = 0xFF,                        // cable car activation?

  // From this point onward, only every second index seems to work.
  // All odd indexes cause the game to freeze when loading rom, not sure.
  MUSIC_256 = 0x100,                     // cable car deactivation?
  MUSIC_257 = 0x101,                     // broken
  MUSIC_258 = 0x102,                     //
  MUSIC_259 = 0x103,                     //
  MUSIC_260 = 0x104,                     //
  MUSIC_261 = 0x105,                     //
  MUSIC_262 = 0x106,                     //
  MUSIC_263 = 0x107,                     //
  MUSIC_264 = 0x108,                     //
  MUSIC_265 = 0x109,                     //
  MUSIC_266 = 0x10A,                     //
  MUSIC_267 = 0x10B,                     //
  MUSIC_268 = 0x10C,                     // no effect
  MUSIC_269 = 0x10D,                     //
  MUSIC_270 = 0x10E,                     //
  MUSIC_271 = 0x10F,                     //
  MUSIC_272 = 0x110,                     //
  MUSIC_273 = 0x111,                     //
  MUSIC_274 = 0x112,                     //
  MUSIC_275 = 0x113,                     //
  MUSIC_276 = 0x114,                     //
  MUSIC_277 = 0x115,                     //
  MUSIC_278 = 0x116,                     //
  MUSIC_279 = 0x117,                     //
  MUSIC_280 = 0x118,                     //
  MUSIC_281 = 0x119,                     //
  MUSIC_282 = 0x11A,                     //
  MUSIC_283 = 0x11B,                     //
  MUSIC_284 = 0x11C,                     //
  MUSIC_285 = 0x11D,                     //
  MUSIC_286 = 0x11E,                     //
  MUSIC_287 = 0x11F,                     //
  MUSIC_288 = 0x120,                     // some kind of warp effect?
  MUSIC_289 = 0x121,                     // broken
  MUSIC_290 = 0x122,                     //
  MUSIC_291 = 0x123,                     //
  MUSIC_292 = 0x124,                     //
  MUSIC_293 = 0x125,                     //
  MUSIC_294 = 0x126,                     //
  MUSIC_295 = 0x127,                     //
  MUSIC_296 = 0x128,                     //
  MUSIC_297 = 0x129,                     //
  MUSIC_298 = 0x12A,                     //
  MUSIC_299 = 0x12B,                     //
  MUSIC_300 = 0x12C,                     //
  MUSIC_301 = 0x12D,                     //
  MUSIC_302 = 0x12E,                     //
  MUSIC_303 = 0x12F,                     //
  MUSIC_304 = 0x130,                     //
  MUSIC_305 = 0x131,                     // broken
  MUSIC_306 = 0x132,                     //
  MUSIC_307 = 0x133,                     //
  MUSIC_308 = 0x134,                     //
  MUSIC_309 = 0x135,                     //
  MUSIC_310 = 0x136,                     //
  MUSIC_311 = 0x137,                     //
  MUSIC_312 = 0x138,                     // Paradox bros appear?
  MUSIC_313 = 0x139,                     // broken
  MUSIC_314 = 0x13A,                     //
  MUSIC_315 = 0x13B,                     //
  MUSIC_316 = 0x13C,                     //
  MUSIC_317 = 0x13D,                     //
  MUSIC_318 = 0x13E,                     //
  MUSIC_319 = 0x13F,                     //
  MUSIC_320 = 0x140,                     //
  MUSIC_321 = 0x141,                     //
  MUSIC_322 = 0x142,                     // some kind of put-put engine effect?
  MUSIC_323 = 0x143,                     //
  MUSIC_324 = 0x144,                     //
  MUSIC_325 = 0x145,                     //
  MUSIC_326 = 0x146,                     //
  MUSIC_327 = 0x147,                     //
  MUSIC_328 = 0x148,                     //
  MUSIC_329 = 0x149,                     //
  MUSIC_330 = 0x14A,                     //
  MUSIC_331 = 0x14B,                     //
  MUSIC_332 = 0x14C,                     //
  MUSIC_333 = 0x14D,                     // broken
  MUSIC_334 = 0x14E,                     // ??
  MUSIC_335 = 0x14F,                     //
  MUSIC_336 = 0x150,                     //
  MUSIC_337 = 0x151,                     //
  MUSIC_338 = 0x152,                     //
  MUSIC_339 = 0x153,                     //
  MUSIC_340 = 0x154,                     //
  MUSIC_341 = 0x155,                     //
  MUSIC_342 = 0x156,                     //
  MUSIC_343 = 0x157,                     //
  MUSIC_344 = 0x158,                     //
  MUSIC_345 = 0x159,                     //
  MUSIC_346 = 0x15A,                     //
  MUSIC_347 = 0x15B,                     //
  MUSIC_348 = 0x15C,                     // Ra's lightning striking (4 times)
  MUSIC_349 = 0x15D,                     //
  MUSIC_350 = 0x15E,                     // unleashing Slifer + roar?
  MUSIC_351 = 0x15F,                     // broken
  MUSIC_352 = 0x160,                     // some kind of teleport effect??
  MUSIC_353 = 0x161,                     // broken
  SFX_NEW_GAME_INTRO_CUTSCENE_1 = 0x162, // fire burning, sinister notes, etc.
  MUSIC_355 = 0x163,                     // broken
  SFX_NEW_GAME_INTRO_CUTSCENE_2 = 0x164, // god cards zooming all around the world
  MUSIC_357 = 0x165,                     // broken
  MUSIC_358 = 0x166,                     // no effect
  MUSIC_359 = 0x167,                     // broken
  MUSIC_360 = 0x168,                     // 4 teleport sounds?
  MUSIC_361 = 0x169,                     // broken
  MUSIC_362 = 0x16A,                     // ??
  MUSIC_363 = 0x16B,                     //
  MUSIC_364 = 0x16C,                     //
  MUSIC_365 = 0x16D,                     //
  MUSIC_366 = 0x16E,                     //
  MUSIC_367 = 0x16F,                     //
  MUSIC_368 = 0x170,                     //
  MUSIC_369 = 0x171,                     //
  MUSIC_370 = 0x172,                     //
  MUSIC_371 = 0x173,                     //
  MUSIC_372 = 0x174,                     //
  MUSIC_373 = 0x175,                     //
  MUSIC_374 = 0x176,                     // ??
  MUSIC_375 = 0x177,                     // broken
  MUSIC_376 = 0x178,                     // god card attacks in overworld?
                                         // ...
  MUSIC_600 = 0x258,                     // Track 69: Yami Yugi (Short Version)
};
