
enum TextIds
{
  TEXT_PLAYER_TURN,             // 08FA15E8;
  TEXT_OPPONENT_TURN,           // 08FA165B; // used for non-link duels
  TEXT_DUEL_VICTORY,            // 08FA1704;
  TEXT_DUEL_LOSS,               // 08FA1776;
  TEXT_DUELIST_LEVEL_INCREASED, // 08FA17FA;
  TEXT_CARD_OBTAINED,           // 08FA18DA;
  TEXT_CAPACITY_INCREASED,      // 08FA1960;
  TEXT_CAPACITY_AND_MONEY,      // 08FA1A69; unused?
  TEXT_MONEY_OBTAINED,          // 08FA1BD9;
  TEXT_ABOUT_DOMINO_OBTAINED,   // 08FA1C84; 
  TEXT_ABOUT_MILLION_OBTAINED,  // 08FA1D84; 
  TEXT_ABOUT_BILLION_OBTAINED,  // 08FA1EA8; 
  TEXT_NO_MONEY_OBTAINED,       // 08FA1FB9; 
  TEXT_TOO_MUCH_MONEY,          // 08FA2079; unused?
  TEXT_TRANSFORMED_INTO,        // 08FA212D; moths/Cocoon of Evolution
  TEXT_SWORDS_REMAIN_EFFECT,    // 08FA21E8;
  TEXT_SWORDS_EFFECT_FADED,     // 08FA2320;
  TEXT_ALL_EXODIA_PIECES,       // 08FA245B;
  TEXT_DESTINY_BOARD_MESSAGE,   // 08FA257B; FINAL message complete
  TEXT_OPPONENT_OUT_OF_LP,      // 08FA26A6;
  TEXT_PLAYER_OUT_OF_LP,        // 08FA2766;
  TEXT_OPPONENT_DECK_OUT,       // 08FA27F7;
  TEXT_PLAYER_DECK_OUT,         // 08FA2938;
  TEXT_OPPONENT_LINK_TURN,      // 08FA2A43; includes the custom name of the link duel opponent?
  TEXT_LINKING,                 // 08FA2AEC;
  TEXT_COMMUNICATION_ERROR      // 08FA2B33;
};
